import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { unzipSync, strFromU8 } from 'fflate'

test('the homepage is a real, fast-to-understand design library', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: /A good idea\. A great identity\./ })).toBeVisible()
  await expect(page.locator('.brand-card')).toHaveCount(12)
  await expect(page.getByRole('status').first()).toContainText('48 identities')
  await expect(page.locator('.repo-hero-panel')).toBeVisible()
  await expect(page.locator('.repo-panel-stats > span')).toHaveCount(3)
  await expect(page.getByRole('link', { name: 'View the repository' })).toHaveAttribute('href', 'https://github.com/arssshi/openform')
  await expect.poll(() => page.locator('.brand-grid img').evaluateAll(images => images.every(image => (image as HTMLImageElement).complete && (image as HTMLImageElement).naturalWidth > 0))).toBe(true)
  expect(errors).toEqual([])
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: testInfo.outputPath('openform-desktop.png'), fullPage: true })
})

test('search, style pages, collection pages, and filters lead to real identities', async ({ page }) => {
  await page.goto('/#library')
  await page.getByRole('textbox', { name: 'Search brand identities' }).fill('botanical')
  await expect(page.locator('.brand-card')).toHaveCount(2)
  await page.getByRole('button', { name: 'Clear search' }).click()
  await page.goto('/styles/futuristic/')
  await expect(page.getByRole('heading', { name: /Futuristic identities/ })).toBeVisible()
  await expect(page.locator('.brand-card')).toHaveCount(6)
  await page.goto('/collections/earthbound/')
  await expect(page.getByRole('heading', { name: 'Earthbound.' })).toBeVisible()
  await expect(page.locator('.brand-card')).toHaveCount(7)
  await page.goto('/#library')
  await page.getByRole('button', { name: 'Filters', exact: true }).click()
  await page.getByLabel('Industry').selectOption('Mobility')
  await expect(page.locator('.brand-card')).toHaveCount(2)
  await expect(page.locator('.brand-card[data-brand="vertex"]')).toHaveCount(1)
})

test('saved identities persist across reload and can be removed', async ({ page }) => {
  await page.goto('/#library')
  await page.getByRole('button', { name: 'Save moss', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Unsave moss', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Show 1 saved identities' }).click()
  await expect(page.locator('.brand-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'Unsave moss', exact: true }).click()
  await expect(page.getByText('Keep a little inspiration for later.')).toBeVisible()
})

test('the full directory is discoverable with stable sorting', async ({ page }) => {
  await page.goto('/#library')
  await page.getByRole('button', { name: 'A little more inspiration' }).click()
  await page.getByRole('button', { name: 'A little more inspiration' }).click()
  await page.getByRole('button', { name: 'A little more inspiration' }).click()
  await expect(page.locator('.brand-card')).toHaveCount(48)
  await page.getByLabel('Sort by').selectOption('az')
  await expect(page.locator('.brand-card').first()).toHaveAttribute('data-brand', 'almanac')
  await expect(page.locator('.identity-directory nav a')).toHaveCount(48)
})

test('an identity has a crawlable page with a clear system and useful tabs', async ({ page }) => {
  await page.goto('/brands/orbit/')
  await expect(page).toHaveTitle(/orbit.*Brand Identity.*Openform/)
  await expect(page.getByRole('heading', { name: 'orbit', exact: true })).toBeVisible()
  await expect(page.getByText('Orbital optimism')).toBeVisible()
  await page.getByRole('tab', { name: 'Applications', exact: true }).click()
  await expect(page.locator('.application-menu button')).toHaveCount(8)
  await page.getByRole('tab', { name: 'Assets 30' }).click()
  await expect(page.locator('.asset-card')).toHaveCount(30)
  await page.getByRole('tab', { name: 'Install theme' }).click()
  await expect(page.getByText('Just say: “install this theme.”')).toBeVisible()
  await expect(page.locator('.code-window').filter({ hasText: '/themes/orbit/theme.css' })).toContainText('/themes/orbit/theme.css')
  await expect(page.locator('iframe')).toHaveCount(1)
})

test('downloaded kits contain original assets, local fonts, and the install contract', async ({ page, request }) => {
  await page.goto('/brands/moss/')
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('link', { name: 'Download kit', exact: true }).click()
  const download = await downloadEvent
  expect(download.suggestedFilename()).toBe('moss-brand-kit.zip')
  const response = await request.get('/downloads/moss-brand-kit.zip')
  expect(response.ok()).toBe(true)
  const kit = unzipSync(new Uint8Array(await response.body()))
  expect(Object.keys(kit)).toContain('fonts/manrope.ttf')
  expect(Object.keys(kit)).toContain('fonts/instrument-serif-italic-OFL.txt')
  expect(Object.keys(kit)).toContain('theme.json')
  expect(Object.keys(kit)).toContain('AI-PROMPT.md')
  expect(Object.keys(kit)).toContain('install-theme.mjs')
  const theme = JSON.parse(strFromU8(kit['theme.json']))
  expect(theme.scope.selector).toBe('[data-openform="moss"]')
  expect(theme.exports).toHaveLength(30)
  expect(strFromU8(kit['theme.css'])).toContain('[data-openform="moss"]')
  expect(strFromU8(kit['lockup.svg'])).not.toContain('<text')
})

test('the design notes page explains the actual install path', async ({ page }) => {
  await page.goto('/guides/install-brand-theme/')
  await expect(page.getByRole('heading', { name: /A new identity/ })).toBeVisible()
  await expect(page.getByText('node install-theme.mjs --target')).toHaveCount(2)
  await expect(page.getByRole('link', { name: /Explore moss and its theme/ })).toHaveAttribute('href', '/brands/moss/#install')
})

test('home and identity pages meet automated WCAG AA checks', async ({ page }) => {
  await page.goto('/')
  const home = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  expect(home.violations.map(item => ({ rule: item.id, targets: item.nodes.map(node => node.target) }))).toEqual([])
  await page.goto('/brands/moss/')
  const identity = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  expect(identity.violations.map(item => ({ rule: item.id, targets: item.nodes.map(node => node.target) }))).toEqual([])
})

test('palettes and prompts can actually be copied', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/brands/moss/')
  await page.getByRole('button', { name: 'Copy Forest #153E35' }).click()
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe('#153E35')
  await page.getByRole('tab', { name: 'Install theme' }).click()
  await page.getByRole('button', { name: 'Copy full implementation prompt' }).click()
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toContain('Install the moss theme')
})

test('source and license dialogs link to real archives and documentation', async ({ page, request }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Licenses', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Openform licenses' })).toBeVisible()
  const license = await request.get('/docs/LICENSE-ASSETS.txt')
  expect(await license.text()).toContain('CC0-1.0')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Open source', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Contribute to Openform' })).toBeVisible()
  const source = await request.get('/downloads/openform-source.zip')
  expect(source.ok()).toBe(true)
  const files = unzipSync(new Uint8Array(await source.body()))
  expect(Object.keys(files)).toContain('src/data/systems.json')
  expect(Object.keys(files)).toContain('scripts/build-site.mjs')
  expect(Object.keys(files).some(file => file.startsWith('original-'))).toBe(false)
})
