import { ArrowUpRight, Check } from 'lucide-react'
import { brandUrl } from '../lib/pages'
import { sitePath } from '../lib/site'

export default function Guide() {
  return <main id="main" className="guide-page container">
    <nav className="breadcrumbs" aria-label="Breadcrumb"><a href={sitePath('/')}>Openform</a><span>/</span><span>Design notes</span></nav>
    <header className="guide-heading"><span className="eyebrow">A PRACTICAL DESIGN NOTE</span><h1>A new identity.<br /><em>Your existing website.</em></h1><p>How to install a complete Openform brand theme, keep your working application, and make the details feel like they belong together.</p></header>
    <div className="guide-layout"><aside className="guide-toc"><span className="eyebrow">IN THIS GUIDE</span><a href="#choose">01 / Choose a starting point</a><a href="#install">02 / Install the files</a><a href="#apply">03 / Apply the system</a><a href="#verify">04 / Check the details</a><a href="#assistant">05 / Use a coding assistant</a></aside><article className="guide-article">
      <section id="choose"><h2>01. Start with a clear idea.</h2><p>A useful brand identity is a relationship between a mark, typography, color, and spacing. Choose a system for the feeling and structure your project needs, rather than one accent color in isolation.</p><p>Explore an identity’s palette and type pairing, try your own words in the playground, and open its working website reference. Our templates keep the presentation simple: a clear heading, one focal visual, and comfortably readable sections. The downloadable applications show how the same decisions can work in print and on screen.</p><p>For this example, we’ll use <a href={brandUrl('moss')}>moss, our botanical identity</a>. Download its complete kit and extract it into a folder you can work from. The original font files, SVGs, stylesheet, installer, and license notices stay together.</p></section>
      <section id="install"><h2>02. Put the actual files in place.</h2><p>The portable installer requires Node.js 18 or newer and no npm dependencies. From the extracted kit folder, run:</p><pre><code>{'node install-theme.mjs --target "/path/to/your/project"'}</code></pre><p>The default destination is <code>public/themes/moss/</code>. If your framework uses a different static-assets root, use <code>--public-dir static</code> or the folder it serves. For a plain static site served directly from its project root, use <code>--public-dir .</code>.</p><p>For an existing Vite or plain HTML document, the installer can also attach the stylesheet and root attribute:</p><pre><code>{'node install-theme.mjs --target "/path/to/project" --html index.html'}</code></pre><p>It keeps the original HTML in a one-time <code>.openform-backup</code> file and avoids duplicate stylesheet links when you run it again. Add <code>--react</code> if you want the optional typed component primitives copied into your source tree.</p></section>
      <section id="apply"><h2>03. Give your components the same language.</h2><p>Load the stylesheet after broad resets and framework styles. Add the identity’s exact <code>data-openform</code> attribute to your existing document root or the intended wrapper. Keeping the theme scoped lets you apply it to a whole website or one chosen area.</p><pre><code>{'<link rel="stylesheet" href="/themes/moss/theme.css">\n\n<div data-openform="moss" class="of-theme">\n  <h1 class="of-display">Your real headline.</h1>\n  <p class="of-body">Your real project description.</p>\n  <a class="of-button" href="/your-route">Get started</a>\n</div>'}</code></pre><p>Use <code>reference.html</code> for the page structure and <code>components.html</code> for controls, cards, forms, and information. The exact class map, numbers, fonts, and paths live in <code>theme.json</code>. Keep your existing navigation, routes, state, data requests, and form handlers; the theme supplies their visual system.</p><p>In Next.js, Vue, Svelte, or Astro, attach the link and attribute in the existing document or root layout. The supplied installation guide includes framework-specific instructions. Keep the fonts next to the stylesheet so their local URLs continue to resolve.</p></section>
      <section id="verify"><h2>04. Check the quiet details.</h2><p>Compare the real page to the working reference at phone, tablet, and desktop widths. A system is only useful if it reads well and behaves properly in your actual application.</p><ul className="guide-checks">{['The CSS, local fonts, and images load without missing requests.', 'The heading and reading faces match the supplied type specification.', 'Reading text has enough contrast, a comfortable line length, and room to breathe.', 'There is no horizontal page overflow at narrow widths.', 'Navigation, routes, forms, and real application state still work.', 'Keyboard focus is visible and reduced-motion preferences are respected.'].map(text => <li key={text}><Check size={17} />{text}</li>)}</ul><p>The ink-on-paper and ink-on-accent pairs are checked for WCAG AA normal text. Support colors are decorative until a specific text pairing has been verified. Avoid adding extra effects or low-contrast details simply because the assets make it possible.</p></section>
      <section id="assistant"><h2>05. Give your assistant concrete instructions.</h2><p>You can ask a coding assistant to apply the system. Put the extracted kit where it can read the files and give it the identity’s one-line request:</p><blockquote>Install the Openform moss theme in this project. Read AI-PROMPT.md and theme.json, run install-theme.mjs against this project’s root, and follow the supplied working references. Preserve the existing content, routes, data, and functionality.</blockquote><p>The full prompt is deliberately ordered. It specifies the framework root, exact paths, numerical design decisions, component classes, and acceptance checks. A smaller model has executable CSS and real examples to follow rather than a vague request to make a page “more modern.”</p><p>The installer places the files; the assistant or developer finishes the component mapping. Ask for the files changed and the checks actually performed. Keep the MIT code notice and original font notices when redistributing those files. The original design artwork and information are CC0.</p><a className="button button-dark" href={brandUrl('moss') + '#install'}>Explore moss and its theme<ArrowUpRight size={17} /></a></section>
    </article></div>
  </main>
}
